site_name: Enkhmurun Bayasgalan
site_description: Collection of random notes on science and engineering topics

theme:
  name: material
  logo: assets/images/logo/logo.png
  favicon: assets/images/logo/logo.png
  custom_dir: material
  language: en
  font:
    text: Roboto
    code: Roboto Mono
  palette: 
    # Palette toggle for light mode
    - scheme: default
      primary: black
      accent: orange
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode

    # # Palette toggle for built-in dark mode
    # - scheme: slate
    #   primary: black
    #   accent: indigo
    #   toggle:
    #     icon: material/toggle-switch-off-outline
    #     name: Switch to light mode

    # Custom dark mode
    - scheme: dark
      primary: black
      accent: orange
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
        
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
    # - navigation.indexes
    - toc.follow
    # - toc.integrate
    - navigation.top

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - md_in_html
  - tables
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

extra_css:
  - assets/stylesheets/extra.css

extra_javascript:
  - assets/javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra:
  generator: false

## Navigation Tree
nav:
  - Home: index.md
  - Matrix Theory: 
    - References: matrix_theory/references.md
    - Norms:
      - Vector Norms: matrix_theory/norms/vector_norms.md
      - Matrix Norms: matrix_theory/norms/matrix_norms.md
    - Matrix Factorization:
      - Singular Value Decomposition: matrix_theory/matrix_factorization/singular_value_decomposition.md
      - QR Decomposition: matrix_theory/matrix_factorization/qr_decomposition.md
      - Cholesky Decomposition: matrix_theory/matrix_factorization/cholesky_decomposition.md
    - Matrix Calculus:
      - Identities: matrix_theory/matrix_calculus/matrix_calculus_identities.md
      - Matrix Calculus: matrix_theory/matrix_calculus/matrix_calculus.md
    - Software Implementation:
      - Storage: matrix_theory/software_implementation/storage.md
      - Multiplication: matrix_theory/software_implementation/multiplication.md

  - Kinematics:
    - Rotations and Cross-Relations:
      - Angular Velocity: kinematics/rotations/angular_velocity.md
      - Rotation Matrix: kinematics/rotations/rotation_matrix.md
      - Euler Angles: kinematics/rotations/euler_angles.md
      - Axis-Angle: kinematics/rotations/axis_angle.md
      - Quaternions: kinematics/rotations/quaternions.md
    - Pose, Rotation, and Matrix Groups: 
      - Matrix Groups and Lie Theory: kinematics/pose_rotation_and_matrix_groups/matrix_groups_and_lie_theory.md
      - Special Orthogonal and Special Euclidean Groups: kinematics/pose_rotation_and_matrix_groups/special_orthogonal_and_special_euclidean_groups.md
      - Difference, Interpolation, and Perturbation: kinematics/pose_rotation_and_matrix_groups/difference_interpolation_and_perturbation.md 
    - Jacobians:
      - Definition of Derivatives: kinematics/jacobians/definition_of_derivatives.md
      - Jacobian with Respect to Euler Angles: kinematics/jacobians_of_rotations_and_poses/jacobian_wrt_euler_angles.md
      - Perturbed Rotations via Euler Angles: kinematics/jacobians_of_rotations_and_poses/perturbed_rotations_via_euler_angles.md
      - Jacobian with Respect to Lie Algebra Vector: kinematics/jacobians_of_rotations_and_poses/jacobian_wrt_lie_algebra_vector.md
      - Perturbed Rotations via Rotation Vector: kinematics/jacobians_of_rotations_and_poses/perturbed_rotations_via_rotation_vector.md
      - Perturbed Poses via Rotation Vector: kinematics/jacobians_of_rotations_and_poses/perturbed_poses_via_rotation_vector.md
    - Optimization on Smooth Manifolds:
      - Interpolation: kinematics/optimization_on_smooth_manifolds/interpolation.md
      - Difference of Rotations: kinematics/optimization_on_smooth_manifolds/difference_of_rotations.md
    - Cartesian Position: kinematics/cartesian_position.md
    - Velocity: kinematics/velocity.md
    - Acceleration: kinematics/acceleration.md
    - Camera Motion:
      - Camera Pose: kinematics/camera_motion/camera_pose.md
    - References: kinematics/references.md
  
  - Estimation Theory:
    - References: estimation_theory/references.md
    - Probability Theory:
      - Terminologies: estimation_theory/probability_theory/terminologies.md
      - Mean and Mode: estimation_theory/probability_theory/sample_mean_and_mode.md
      - Variability Measures: estimation_theory/probability_theory/sample_variability_measures.md
      - Univariate Sample Example: assets/jupyter/probability/cellarea_analysis.ipynb
      - Multivariate Sample Properties: estimation_theory/probability_theory/multivariate_sample_properties.md
      - Observations as Time Series: estimation_theory/probability_theory/observations_as_time_series.md
      - Probability: estimation_theory/probability_theory/probability.md
      - Bayes' Rule: estimation_theory/probability_theory/bayes_rule.md
      - Random Variables: estimation_theory/probability_theory/random_variables/random_variables.md
      - Transformations of Random Variables: estimation_theory/probability_theory/random_variables/transformations_of_random_variables.md
      - Multiple Random Variables: estimation_theory/probability_theory/random_variables/multiple_random_variables.md
      - Distributions:
        - Discrete Uniform Distribution: estimation_theory/probability_theory/discrete_distributions/discrete_uniform_distribution.md
        - Uniform Distribution: estimation_theory/probability_theory/continuous_distributions/uniform_distribution.md
        - Bernoulli and Binomial Distributions: estimation_theory/probability_theory/discrete_distributions/bernoulli_and_binomial_distributions.md
        - Poisson Distribution: estimation_theory/probability_theory/discrete_distributions/poisson_distribution.md
        - Geometric Distribution: https://en.wikipedia.org/wiki/Geometric_distribution
        - Multinomial Distribution: https://en.wikipedia.org/wiki/Multinomial_distribution
        - Exponential Distribution: estimation_theory/probability_theory/continuous_distributions/exponential_distribution.md
        - Gamma Distribution: estimation_theory/probability_theory/continuous_distributions/gamma_distribution.md
        - Logistic Distribution: https://en.wikipedia.org/wiki/Logistic_distribution
        - Normal Distribution: estimation_theory/probability_theory/continuous_distributions/normal_distribution.md
        - Chi-square Distribution: estimation_theory/probability_theory/continuous_distributions/chi_square_distribution.md
        - Beta Distribution: https://en.wikipedia.org/wiki/Beta_distribution
        - Weibull Distribution: https://en.wikipedia.org/wiki/Weibull_distribution#:~:text=In%20probability%20theory%20and%20statistics,spends%20on%20a%20web%20page.
    - Optimization:
      - Sets:
        - Norms, Distance, and Unit Ball: optimization/sets/norms_distance_unit_ball.md
        - Open and Closed Sets: optimization/sets/open_and_closed_sets.md
        - Geometry: optimization/sets/geometry.md
        - Convex Sets: optimization/sets/convex_sets.md
        - Nonconvex Sets: optimization/sets/nonconvex_sets.md
      - Functions:
        - Functions, Gradient, Jacobian, Hessian: optimization/functions/functions.md
        - Convex Functions: optimization/functions/convex_functions.md
        - Nonconvex Functions: optimization/functions/nonconvex_functions.md
      - Optimization Problem Formulation: optimization/optimization_problem_formulation.md
      - Duality Theory: optimization/duality.md
      - Unconstrained Optimization:
        - Optimality Conditions: optimization/unconstrained_optimization/optimality_conditions.md
        - Gradient Desent: optimization/unconstrained_optimization/gradient_descent.md
        - Newton's Method: optimization/unconstrained_optimization/newton_method.md
        - Quasi-Newton Method: optimization/unconstrained_optimization/quasi_newton_method.md
        - Gauss-Netwon Method: optimization/unconstrained_optimization/gauss_newton_method.md
        - Golden Section: optimization/unconstrained_optimization/golden_section.md
        - Quadratic Fit: optimization/unconstrained_optimization/quadratic_fit.md
        - Nelder-Mead Method: optimization/unconstrained_optimization/nelder_mead_method.md
      - Linear Programming:
        - Modelling Using Linear Programs: optimization/linear_programming/modelling_using_linear_programs.md
        - Algrebraic Aspects: optimization/linear_programming/algebraic_aspects.md
        - Simplex Method: optimization/linear_programming/simplex_method.md
        - Linear Stochastic Program: optimization/linear_programming/linear_stochastic_program.md
        - Nonlinear Program: optimization/linear_programming/nonlinear_program.md
        - Robust Optimization: optimization/linear_programming/robust_optimization.md
        - Column and Constraint Generation: optimization/linear_programming/column_and_constraint_generation.md
        - Dantzig-Wolfe Decomposition: optimization/linear_programming/dantzig_wolfe_decomposition.md
      - Nonlinear Programming:
        - Least Squares: optimization/nonlinear_programming/least_squares.md
      - Perturbation Methods: optimization/perturbation_methods.md
      - Integer Programming:
        - Discrete Optimization Models: optimization/integer_programming/discrete_optimization_models.md
        - Modelling Nonconvex Functions: optimization/integer_programming/modelling_nonconvex_functions.md
        - Modelling Nonconvex Sets: optimization/integer_programming/modelling_nonconvex_sets.md
        - Modelling Logical Relations: optimization/integer_programming/modelling_logical_relations.md
    - Statistical Estimators:
      - Moment-Matching Estimator: estimation_theory/statistical_estimators/moment_matching_estimator.md
      - Maximum Likelihood Estimator: estimation_theory/statistical_estimators/maximum_likelihood_estimator.md
    - Bayesian Inference:
      - Bayesian Inference: estimation_theory/bayesian_inference/bayesian_inference.md
      - Bayesian Network: estimation_theory/bayesian_inference/bayesian_network.md
      - Maximum a Posteriori Estimator: estimation_theory/bayesian_inference/maximum_a_posteriori_estimator.md
    - Least Squares Estimator:
      - Least Squares: estimation_theory/least_squares_estimator/least_squares.md
      - Linear Least Squares: estimation_theory/least_squares_estimator/linear_least_squares.md
      - Linear Weighed Least Squares: estimation_theory/least_squares_estimator/linear_weighted_least_squares.md
      - Linear Recursive Least Squares: estimation_theory/least_squares_estimator/linear_recursive_least_squares.md
      - Nonlinear Least Squares: estimation_theory/least_squares_estimator/nonlinear_least_squares.md
      - Least Squares with Dynamics: estimation_theory/least_squares_estimator/least_squares_with_dynamics.md
    - Kalman Filter:
      - Discrete-Time Kalman Filter: estimation_theory/kalman_filter/discrete_time_kalman_filter.md

    - Extended Kalman Filter:
      - Continuous-Time EKF: estimation_theory/continuous_time_ekf.md
    - Factor Graphs:
      - Definition: estimation_theory/factor_graph/definition.md
      - Representations: estimation_theory/factor_graph/representations.md
      - Using Factor Graph:
        - Simple Averaging: estimation_theory/factor_graph/using_factor_graph/simple_averaging.md
        - Weighted Averaging: estimation_theory/factor_graph/using_factor_graph/weighted_averaging.md
        - Weighted Non-Linear Least Squares: estimation_theory/factor_graph/using_factor_graph/weighted_non_linear_least_squares.md
        - Dynamical Systems: estimation_theory/factor_graph/using_factor_graph/dynamical_systems.md

  - Navigation:
    - References: navigation/references.md
    - Coordinate Frames: navigation/coordinate_frames/coordinate_frames.md
    - Geodesy:
      - Primer on Geodesy: navigation/geodesy/primer.md
      - ECEF To Curvilinear Position: navigation/geodesy/ecef_to_curvilinear.md
      - Orthometric Height: navigation/geodesy/orthometric_height.md
      - Rotation of Earth: navigation/geodesy/rotation_of_earth.md
      - Gravity Models: navigation/geodesy/gravity_models.md
      - Frame Transformations: navigation/geodesy/frame_transformations.md
    - IMU and Gravity Models: 
      - IMU Measurements: navigation/imu_and_gravity_models/imu_measurements.md
      - IMU Error Models: navigation/imu_and_gravity_models/imu_error_models.md
      - Inertial Navigation Equations: navigation/imu_and_gravity_models/inertial_navigation_equations.md
    - Inertial Navigation:
      - IMU: navigation/inertial_navigation/imu.md
      - Architecture: navigation/inertial_navigation/inertial_navigation_architecture.md
      - Navigation Equations in ECI Frame: navigation/inertial_navigation/inertial_navigation_ECI.md
      - Navigation Equations in ECEF Frame: navigation/inertial_navigation/inertial_navigation_ECEF.md
      - Navigation Equations in Local Tangent-Plane Frame: navigation/inertial_navigation/inertial_navigation_local_tangent_plane.md
    - Radio Positioning:
      - Position by Ranging: 
        - Ranging: navigation/radio_positioning/ranging/tof_methods.md
        - Positioning from Passive Ranging: navigation/radio_positioning/ranging/positioning_from_passive_ranging.md
      - Angular Position: navigation/radio_positioning/anglular_position.md
      - Time Standards: navigation/time/time_standards.md
    - GPS:
        - Time: navigation/gps/time.md
        - GPS Signals: navigation/gps/gps_signals.md
        - GPS Receiver: navigation/gps/gps_receiver.md

  - Computer Vision:
    - Termanologies: computer_vision/termanologies.md
    - Image Processing:
      - Correlation Filter: computer_vision/image_processing/correlation_filter.md
    - Image Features:
      - ORB: computer_vision/image_features/orb.md
    - Two-View Geometry:
      - Epipolar Geometry: computer_vision/two_view_geometry/epipolar_geometry.md
      - Essential and Fundamental Matrix: computer_vision/two_view_geometry/essential_and_fundamental_matrix.md
      - Homography: computer_vision/two_view_geometry/homography.md
    - Image Compression:
      - Compression via Low-Rank Matrix Approximation: computer_vision/image_compression/compression_by_low_rank_matrix_approximation.md
  - Software:
    - Concurrency:
      - OpenMP: 
        - Basic Usage: software/concurrency/open_mp/basic_usage.md
        - Examples: 
          - Calculating PI: software/concurrency/open_mp/examples/calculating_pi.md
  - Papers:
    - Software: papers/software.md
  
  - Notation and Nomenclature: notation_and_nomenclature/notation_and_nomenclature.md

plugins:
  - search
  - mkdocs-jupyter:
      kernel_name: python3
      execute: true
      allow_errors: false
      execute_ignore:
        - "temp/*.ipynb"