site_name: Enkhmurun Bayasgalan
site_description: Collection of random notes on science and engineering topics

theme:
  name: material
  logo: assets/images/logo/logo.png
  favicon: assets/images/logo/logo.png
  custom_dir: material
  language: en
  font:
    text: Roboto
    code: Roboto Mono
  palette: 
    # Palette toggle for light mode
    - scheme: default
      primary: black
      accent: orange
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode

    # # Palette toggle for dark mode
    # - scheme: slate
    #   primary: black
    #   accent: indigo
    #   toggle:
    #     icon: material/toggle-switch-off-outline
    #     name: Switch to light mode

    # Custom dark mode
    - scheme: dark
      primary: black
      accent: orange
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
        
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.path
    # - navigation.indexes
    - toc.follow
    - toc.integrate
    - navigation.top

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - md_in_html
  - tables
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

extra_css:
  - assets/stylesheets/extra.css

extra_javascript:
  - assets/javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra:
  generator: false

## Navigation Tree
nav:
  - Home: index.md
  - Mathematics:
    - References: math/references.md
    - Cauchy-Schwartz Inequality: math/cauchy_schwarz_inequality.md
    - Sets:
      - Norms, Distance, and Unit Ball: math/sets/norms_distance_unit_ball.md
      - Open and Closed Sets: math/sets/open_and_closed_sets.md
      - Geometry: math/sets/geometry.md
      - Convex Sets: math/sets/convex_sets.md
      - Nonconvex Sets: math/sets/nonconvex_sets.md
    - Functions:
      - Functions, Gradient, Jacobian, Hessian: math/functions/functions.md
      - Convex Functions: math/functions/convex_functions.md
      - Nonconvex Functions: math/functions/nonconvex_functions.md
    - Matrix Calculus: math/matrix_calculus.md
    - Matrix Calculus Identities: math/matrix_calculus_identities.md
    - Matrix Factorization: math/matrix_factorization/singular_value_decomposition.md
    - Perturbation Methods: math/perturbation_methods.md
    - Optimization:
      - References: math/optimization/references.md
      - Optimization Problem Formulation: math/optimization/optimization_problem_formulation.md
      - Duality Theory: math/optimization/duality.md
      - Unconstrained Optimization:
        - Optimality Conditions: math/optimization/unconstrained_optimization/optimality_conditions.md
        - Gradient Desent: math/optimization/unconstrained_optimization/gradient_descent.md
        - Newton's Method: math/optimization/unconstrained_optimization/newton_method.md
        - Quasi-Newton Method: math/optimization/unconstrained_optimization/quasi_newton_method.md
        - Golden Section: math/optimization/unconstrained_optimization/golden_section.md
        - Quadratic Fit: math/optimization/unconstrained_optimization/quadratic_fit.md
        - Nelder-Mead Method: math/optimization/unconstrained_optimization/nelder_mead_method.md
      - Linear Programming:
        - Modelling Using Linear Programs: math/optimization/linear_programming/modelling_using_linear_programs.md
        - Algrebraic Aspects: math/optimization/linear_programming/algebraic_aspects.md
        - Simplex Method: math/optimization/linear_programming/simplex_method.md
        - Linear Stochastic Program: math/optimization/linear_programming/linear_stochastic_program.md
        - Nonlinear Program: math/optimization/linear_programming/nonlinear_program.md
        - Robust Optimization: math/optimization/linear_programming/robust_optimization.md
        - Column and Constraint Generation: math/optimization/linear_programming/column_and_constraint_generation.md
        - Dantzig-Wolfe Decomposition: math/optimization/linear_programming/dantzig_wolfe_decomposition.md
      - Nonlinear Programming:
        - Least Squares: math/optimization/nonlinear_programming/least_squares.md
  
  - Kinematics:
    - References: kinematics/references.md
    - Notation and Nomenclature: kinematics/notation_and_nomenclature.md
    - Attitude and Geometry:
      - Transformation and Rotation Matrix: kinematics/geometry/transformation_and_rotation.md
      - Euler Angles: kinematics/geometry/euler_angles.md
      - Axis Angle: kinematics/geometry/axis_angle.md
      - Quaternions: kinematics/geometry/quaternions.md
      - Attitude Visualization: kinematics/geometry/pangolin_visualization.md
      - Derivative of Rotation Matrix: kinematics/geometry/derivative_of_rotation_matrix.md
    - Angular Rate: kinematics/angular_rate.md
    - Cartesian Position: kinematics/cartesian_position.md
    - Velocity: kinematics/velocity.md
    - Acceleration: kinematics/acceleration.md
  
  - State Estimation:
    - References: state_estimation/references.md
    - Least Squares:
      - Least Squares: state_estimation/least_squares/least_squares.md
      - Weighed Least Squares: state_estimation/least_squares/weighted_least_squares.md

    - Extended Kalman Filter:
      - Continuous-Time EKF: state_estimation/continuous_time_ekf.md
  
  - Computer Vision:
    - Image Compression:
      - Compression via Low-Rank Matrix Approximation: computer_vision/image_compression/compression_by_low_rank_matrix_approximation.md

  - Navigation:
    - References: navigation/references.md
    - Notation & Nomenclature: navigation/notation_and_nomenclature.md
    - Coordinate Frames: navigation/coordinate_frames.md
    - Geodesy:
      - Geodesy: navigation/geodesy.md
      - Geodetic Coordinates: navigation/geodetic_coordinates.md
      - ECEF To Curvilinear Position: navigation/ecef_to_curvilinear.md
      - Orthometric Height: navigation/orthometric_height.md
      - Mercator Projection: navigation/mercator_projection.md
      - Rotation of Earth: navigation/rotation_of_earth.md
      - Gravity Models: navigation/gravity_models.md
      - Frame Transformations: navigation/frame_transformations.md
    - Inertial Navigation:
      - IMU: navigation/imu.md
      - Architecture: navigation/inertial_navigation_architecture.md
      - Navigation Equations in ECI Frame: navigation/inertial_navigation_ECI.md
      - Navigation Equations in ECEF Frame: navigation/inertial_navigation_ECEF.md
      - Navigation Equations in Local Tangent-Plane Frame: navigation/inertial_navigation_local_tangent_plane.md