site_name: Enkhmurun Bayasgalan
site_description: Collection of random notes on science and engineering topics

theme:
  name: material
  logo: assets/images/logo/logo.png
  favicon: assets/images/logo/logo.png
  custom_dir: material
  language: en
  font:
    text: Roboto
    code: Roboto Mono
  palette: 
    # Palette toggle for light mode
    - scheme: default
      primary: black
      accent: orange
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode

    # # Palette toggle for built-in dark mode
    # - scheme: slate
    #   primary: black
    #   accent: indigo
    #   toggle:
    #     icon: material/toggle-switch-off-outline
    #     name: Switch to light mode

    # Custom dark mode
    - scheme: dark
      primary: black
      accent: orange
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
        
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
    # - navigation.indexes
    - toc.follow
    # - toc.integrate
    - navigation.top

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - md_in_html
  - tables
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

extra_css:
  - assets/stylesheets/extra.css

extra_javascript:
  - assets/javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra:
  generator: false

## Navigation Tree
nav:
  - Home: index.md
  - Matrix Theory: 
    - References: matrix_theory/references.md
    - Norms:
      - Vector Norms: matrix_theory/norms/vector_norms.md
      - Matrix Norms: matrix_theory/norms/matrix_norms.md
    - Matrix Factorization:
      - Singular Value Decomposition: matrix_theory/matrix_factorization/singular_value_decomposition.md
    - Matrix Calculus:
      - Identities: matrix_theory/matrix_calculus/matrix_calculus_identities.md
      - Matrix Calculus: matrix_theory/matrix_calculus/matrix_calculus.md
  - Mathematics:
    - References: mathematics/references.md
    - Cauchy-Schwartz Inequality: mathematics/cauchy_schwarz_inequality.md
    - Sets:
      - Norms, Distance, and Unit Ball: mathematics/sets/norms_distance_unit_ball.md
      - Open and Closed Sets: mathematics/sets/open_and_closed_sets.md
      - Geometry: mathematics/sets/geometry.md
      - Convex Sets: mathematics/sets/convex_sets.md
      - Nonconvex Sets: mathematics/sets/nonconvex_sets.md
    - Functions:
      - Functions, Gradient, Jacobian, Hessian: mathematics/functions/functions.md
      - Convex Functions: mathematics/functions/convex_functions.md
      - Nonconvex Functions: mathematics/functions/nonconvex_functions.md
    - Perturbation Methods: mathematics/perturbation_methods.md
    - Probability and Statistics:
      - References: mathematics/probability_and_statistics/references.md
      - Termanologies: mathematics/probability_and_statistics/termanologies.md
      - The Sample and Its Properties:
        - Location Measures: mathematics/probability_and_statistics/the_sample_and_its_properties/location_measures.md
        - Variability Measures: mathematics/probability_and_statistics/the_sample_and_its_properties/variability_measures.md
        - Univariate Sample Example: assets/jupyter/probability/cellarea_analysis.ipynb
        - Multivariate Sample Properties: mathematics/probability_and_statistics/the_sample_and_its_properties/multivariate_sample_properties.md
        - Observations as Time Series: mathematics/probability_and_statistics/the_sample_and_its_properties/observations_as_time_series.md
    - Optimization:
      - References: mathematics/optimization/references.md
      - Optimization Problem Formulation: mathematics/optimization/optimization_problem_formulation.md
      - Duality Theory: mathematics/optimization/duality.md
      - Unconstrained Optimization:
        - Optimality Conditions: mathematics/optimization/unconstrained_optimization/optimality_conditions.md
        - Gradient Desent: mathematics/optimization/unconstrained_optimization/gradient_descent.md
        - Newton's Method: mathematics/optimization/unconstrained_optimization/newton_method.md
        - Quasi-Newton Method: mathematics/optimization/unconstrained_optimization/quasi_newton_method.md
        - Gauss-Netwon Method: mathematics/optimization/unconstrained_optimization/gauss_newton_method.md
        - Golden Section: mathematics/optimization/unconstrained_optimization/golden_section.md
        - Quadratic Fit: mathematics/optimization/unconstrained_optimization/quadratic_fit.md
        - Nelder-Mead Method: mathematics/optimization/unconstrained_optimization/nelder_mead_method.md
      - Linear Programming:
        - Modelling Using Linear Programs: mathematics/optimization/linear_programming/modelling_using_linear_programs.md
        - Algrebraic Aspects: mathematics/optimization/linear_programming/algebraic_aspects.md
        - Simplex Method: mathematics/optimization/linear_programming/simplex_method.md
        - Linear Stochastic Program: mathematics/optimization/linear_programming/linear_stochastic_program.md
        - Nonlinear Program: mathematics/optimization/linear_programming/nonlinear_program.md
        - Robust Optimization: mathematics/optimization/linear_programming/robust_optimization.md
        - Column and Constraint Generation: mathematics/optimization/linear_programming/column_and_constraint_generation.md
        - Dantzig-Wolfe Decomposition: mathematics/optimization/linear_programming/dantzig_wolfe_decomposition.md
      - Nonlinear Programming:
        - Least Squares: mathematics/optimization/nonlinear_programming/least_squares.md
      - Integer Programming:
        - Discrete Optimization Models: mathematics/optimization/integer_programming/discrete_optimization_models.md
        - Modelling Nonconvex Functions: mathematics/optimization/integer_programming/modelling_nonconvex_functions.md
        - Modelling Nonconvex Sets: mathematics/optimization/integer_programming/modelling_nonconvex_sets.md
        - Modelling Logical Relations: mathematics/optimization/integer_programming/modelling_logical_relations.md
  
  - Kinematics:
    - References: kinematics/references.md
    - Pose and Attitude: kinematics/pose_and_attitude/pose_and_attitude.md
    - Rotations:
      - Rotation Matrices: kinematics/rotations/rotation_matrices.md
      - Euler Angles: kinematics/rotations/euler_angles.md
      - Axis Angle: kinematics/rotations/axis_angle.md
      - Quaternions: kinematics/rotations/quaternions.md
      - Attitude Visualization: kinematics/rotations/pangolin_visualization.md
    - Angular Velocity: kinematics/angular_velocity.md
    - Cartesian Position: kinematics/cartesian_position.md
    - Velocity: kinematics/velocity.md
    - Acceleration: kinematics/acceleration.md
    - Lie Theory: 
      - Key Indentities: kinematics/lie_theory/key_identities.md
      - Lie Groups and Lie Algebra: kinematics/lie_theory/lie_group_algebra.md 
      - SO(3): kinematics/lie_theory/so3.md
      - SE(3): kinematics/lie_theory/se3.md
      - BCH and Perturbed Rotations: kinematics/lie_theory/bch_and_perturbed_rotations.md
      - SO(3) Jacobians: kinematics/lie_theory/so3_jacobians.md
      - SE(3) Jacobians: kinematics/lie_theory/se3_jacobians.md
  
  - State Estimation:
    - References: state_estimation/references.md
    - Least Squares:
      - Least Squares: state_estimation/least_squares/least_squares.md
      - Weighed Least Squares: state_estimation/least_squares/weighted_least_squares.md

    - Extended Kalman Filter:
      - Continuous-Time EKF: state_estimation/continuous_time_ekf.md

  - Navigation:
    - References: navigation/references.md
    - Coordinate Frames: navigation/coordinate_frames/coordinate_frames.md
    - Geodesy:
      - Primer on Geodesy: navigation/geodesy/primer.md
      - ECEF To Curvilinear Position: navigation/geodesy/ecef_to_curvilinear.md
      - Orthometric Height: navigation/geodesy/orthometric_height.md
      - Rotation of Earth: navigation/geodesy/rotation_of_earth.md
      - Gravity Models: navigation/geodesy/gravity_models.md
      - Frame Transformations: navigation/geodesy/frame_transformations.md
    - Inertial Navigation:
      - IMU: navigation/inertial_navigation/imu.md
      - Architecture: navigation/inertial_navigation/inertial_navigation_architecture.md
      - Navigation Equations in ECI Frame: navigation/inertial_navigation/inertial_navigation_ECI.md
      - Navigation Equations in ECEF Frame: navigation/inertial_navigation/inertial_navigation_ECEF.md
      - Navigation Equations in Local Tangent-Plane Frame: navigation/inertial_navigation/inertial_navigation_local_tangent_plane.md
    - Radio Positioning:
      - Position by Ranging: 
        - Ranging: navigation/radio_positioning/ranging/tof_methods.md
        - Positioning from Passive Ranging: navigation/radio_positioning/ranging/positioning_from_passive_ranging.md
      - Angular Position: navigation/radio_positioning/anglular_position.md
      - Time Standards: navigation/time/time_standards.md
    - GNSS:
      - GPS:
        - GPS Signals: navigation/gnss/gps/gps_signals.md
        - GPS Receiver: navigation/gnss/gps/gps_receiver.md
        - GPS Time: navigation/gnss/gps/gps_time.md

  - Computer Vision:
    - Image Compression:
      - Compression via Low-Rank Matrix Approximation: computer_vision/image_compression/compression_by_low_rank_matrix_approximation.md
  - Papers:
    - Software: papers/software.md
  
  - Notation and Nomenclature: notation_and_nomenclature/notation_and_nomenclature.md

plugins:
  - mkdocs-jupyter:
      kernel_name: python3
      execute: true
      allow_errors: false
      execute_ignore:
        - "temp/*.ipynb"